### ISSUE TITLE
How can I set a specific copy/backup handler?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [CrendKing/proxy-copy-handler#1]
It seems need to set the registry value, right? 

I thought there's default handler, but I can't find.

Thanks.

**Comment by CrendKing** [comment]
Sorry for not documenting the usage.

* Create registry key at `HKEY_CURRENT_USER\Software\ProxyCopyHandler`.
* Create String value named `CopierPath`. It is the path to the copier.
* Create String value named `CopierArgs`. It is the arguments to be passed to the copier.
* If an optional DWORD value `StartMinimized` is valued non-zero, the copier process is created minimized.

FYI, the relevant code is at https://github.com/CrendKing/proxy-copy-handler/blob/master/src/hook.cpp.

Hope it helps.

**Comment by luceat-lux-vestra** [comment]
I guess it's tied with fastcopy.
If it's correct, then I can't set another application that has different cmdline format.

Needs to customize a bit to specific utility want to use I guess.

I hope to make a file operation handler like TeraCopy/FastCopy but more focused on performance and light usage(no plans to implement features that power users needs).

Windows default file copy and delete in gui is sucks, 
Command line tools are much better, like robocooy and rmdir.

Thanks for inspiration.

**Comment by CrendKing** [comment]
Oh yeah, I guess you meant [these lines](https://github.com/CrendKing/proxy-copy-handler/blob/e6684e5620e2448a5cd68aaa56fddf0822dc447a/src/hook.cpp#L168). I wrote this long time ago when I just wanted to support FastCopy. If you want, feel free to fork and support other tools.
